import { useEffect, useRef, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, X, Inbox, ChevronRight, LoaderCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { date, dateTime, initials, money } from './api';
import { calculateAmount } from './calculator';
import { mediaUrl, PhotoViewer } from './images';
import type { Customer, Entry } from './types';
export function Avatar({ name, index = 0, photo }: { name: string; index?: number; photo?: string }) {
  const [view, setView] = useState(false);
  return <><span className={`avatar color-${index % 6}`} role={photo ? 'button' : undefined} tabIndex={photo ? 0 : undefined} aria-label={photo ? `View ${name}'s profile photo` : undefined} onClick={e => { if (photo) { e.preventDefault(); e.stopPropagation(); setView(true); } }} onKeyDown={e => { if (photo && ['Enter', ' '].includes(e.key)) { e.preventDefault(); e.stopPropagation(); setView(true); } }}>{photo ? <img loading="lazy" crossOrigin="use-credentials" src={mediaUrl(photo)} alt=""/> : initials(name)}</span>{view && photo && <PhotoViewer src={photo} name={name} onClose={() => setView(false)}/>}</>;
}
export function Empty({ title = 'A fresh start', text = 'Your records will appear here.', action }: { title?: string; text?: string; action?: React.ReactNode }) { return <div className="empty"><span><Inbox size={28}/></span><h3>{title}</h3><p>{text}</p>{action}</div>; }
export function TransactionTable({ entries, customers, onReverse, compact = false }: { entries: Entry[]; customers: Customer[]; onReverse?: (entry: Entry) => void; compact?: boolean }) {
  return entries.length ? <div className="table-scroll"><table><thead><tr><th>Customer</th><th>Transaction</th>{!compact && <th>Note</th>}<th>Date</th><th className="right">Amount</th>{onReverse && <th/>}</tr></thead><tbody>{entries.map((e, i) => { const c = customers.find(c => c._id === e.customerId); return <tr key={e._id}><td><Link to={`/customers/${e.customerId}`} className="person"><Avatar name={c?.name || 'Customer'} index={customers.indexOf(c!)} photo={c?.photo}/><span><strong>{c?.name || 'Customer'}</strong><small>{compact ? e.note : c?.mobile}</small></span></Link></td><td><span className={`badge ${e.delta < 0 ? 'green' : e.kind === 'reversal' ? 'neutral' : 'orange'}`}>{e.delta < 0 ? <ArrowDownLeft size={12}/> : <ArrowUpRight size={12}/>} {e.kind === 'reversal' ? 'Reversal' : e.action === 'advance' ? 'Advance' : e.action === 'payment' || (!e.action && e.kind === 'received') ? 'Payment' : 'Udhar'}</span><small className="entry-author">{e.kind === 'reversal' ? 'Correction' : e.kind === 'given' ? 'You gave' : 'You received'}</small></td>{!compact && <td className="muted">{e.note || '—'}{e.sourceEntryId && <small className="entry-author">Added by {c?.name}</small>}{e.attachmentId && <a className="text-button attachment-link" href={mediaUrl(`/api/v1/media/attachment/${e.attachmentId}`)} target="_blank" rel="noreferrer">View photo</a>}</td>}<td className="muted">{dateTime(e.date)}</td><td className={`right amount ${e.delta < 0 ? 'positive' : ''}`}>{e.delta < 0 ? '+' : ''}{money(e.amount)}</td>{onReverse && <td>{e.kind !== 'reversal' && !e.billId && !e.sourceEntryId && !entries.some(r => r.reversalOf === e._id) && <button className="text-button" onClick={() => onReverse(e)}>Reverse</button>}</td>}</tr>; })}</tbody></table></div> : <Empty title="Your first entry starts here" text="Add a customer, then record credit or a payment."/>;
}
export function SectionHeader({ title, subtitle, action }: { title: string; subtitle?: string; action?: React.ReactNode }) { return <div className="section-heading"><div><h3>{title}</h3>{subtitle && <p>{subtitle}</p>}</div>{action}</div>; }
export function ViewAll({ to, children = 'View all' }: { to: string; children?: React.ReactNode }) { return <Link className="view-all" to={to}>{children}<ChevronRight size={15}/></Link>; }
export function Calculator() {
  const [expression, setExpression] = useState(''), [error, setError] = useState('');
  const press = (key: string) => { setError(''); setExpression(current => key === 'C' ? '' : key === '⌫' ? current.slice(0, -1) : (current + key).slice(0, 200)); };
  const calculate = (button: HTMLButtonElement) => {
    try {
      const value = calculateAmount(expression).toFixed(2);
      const input = button.closest('form')?.querySelector<HTMLInputElement>('input[name="amount"]');
      if (!input) throw new Error('Open an entry to use the calculated amount.');
      input.value = value; input.dispatchEvent(new Event('input', { bubbles: true })); setExpression(value); setError('');
    } catch (e) { setError((e as Error).message); }
  };
  return <div className="credit-calculator"><label>Quick calculator<input aria-label="Calculation" value={expression} placeholder="e.g. 200 + 10%" maxLength={200} onChange={e => { setExpression(e.target.value); setError(''); }} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); (e.currentTarget.closest('.credit-calculator')?.querySelector('.calculator-equals') as HTMLButtonElement)?.click(); } }}/></label><div className="calculator-keys">{['7','8','9','/','4','5','6','*','1','2','3','-','0','.','%','+','(',')'].map(key => <button type="button" key={key} onClick={() => press(key)}>{key === '/' ? '÷' : key === '*' ? '×' : key}</button>)}<button type="button" onClick={() => press('C')}>Clear</button><button type="button" aria-label="Delete last calculator character" onClick={() => press('⌫')}>⌫</button><button type="button" className="calculator-equals" onClick={e => calculate(e.currentTarget)}>= Use amount</button></div>{error && <div className="form-error" role="alert">{error}</div>}<small>200 + 10% = 220 · 200 × 10% = 20. Amounts round to two decimals.</small></div>;
}
export type Field = { name: string; label: string; type?: string; placeholder?: string; required?: boolean; options?: { value: string; label: string }[]; value?: string | number; min?: string; max?: string; step?: string; help?: string };
export function FormDialog({ title, subtitle, layout, fields, submitLabel = 'Save', onClose, onSubmit, children }: { title: string; subtitle?: string; layout?: 'entry' | 'customer'; fields: Field[]; submitLabel?: string; onClose: () => void; onSubmit: (data: Record<string, string>) => Promise<void>; children?: React.ReactNode }) {
  const dialog = useRef<HTMLDialogElement>(null); const [error, setError] = useState(''), [busy, setBusy] = useState(false);
  useEffect(() => { dialog.current?.showModal(); const original = document.body.style.overflow; document.body.style.overflow = 'hidden'; return () => { document.body.style.overflow = original; }; }, []);
  return <dialog className={`modal ${layout ? `modal-${layout}` : ''}`} aria-label={title} ref={dialog} onCancel={e => { if (busy) e.preventDefault(); else onClose(); }}><div className="modal-heading"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button className="icon-button" aria-label="Close dialog" onClick={onClose} disabled={busy}><X size={20}/></button></div><form onSubmit={async e => { e.preventDefault(); setError(''); setBusy(true); try { if (e.currentTarget.querySelector('[data-uploading="true"]')) throw new Error('Wait for the photo upload to finish.'); await onSubmit(Object.fromEntries(new FormData(e.currentTarget)) as Record<string, string>); onClose(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }}><div className="modal-fields">{fields.map(f => <label className={`field-${f.name}`} key={f.name}>{f.label}{f.type === 'textarea' ? <textarea name={f.name} defaultValue={f.value} placeholder={f.placeholder} required={f.required} maxLength={500}/> : f.options ? <select name={f.name} defaultValue={f.value || ''} required={f.required}><option value="" disabled>Select…</option>{f.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}</select> : <input name={f.name} type={f.type || 'text'} inputMode={f.name === 'amount' ? 'none' : f.type === 'tel' ? 'tel' : undefined} defaultValue={f.value ?? (f.type === 'tel' && f.required ? '+91 ' : undefined)} placeholder={f.placeholder} required={f.required} min={f.min} max={f.max} step={f.step} maxLength={f.type === 'password' ? 128 : 500}/>} {f.help && <small>{f.help}</small>}</label>)}{children}{error && <div className="form-error" role="alert">{error}</div>}</div><div className="modal-footer"><button type="button" className="button" onClick={onClose} disabled={busy}>Cancel</button><button className="button primary" disabled={busy}>{busy && <LoaderCircle size={16} className="spin"/>}{busy ? 'Saving…' : submitLabel}</button></div></form></dialog>;
}
